const state={data:null,mode:"structured_signed",seed:31,experience:5};
const labels={standard:"Standard CNN",random_signed:"Random signed",structured_signed:"Structured signed"};
const descriptions={standard:"No explicit lateral interaction. The 64-channel backbone representation passes directly to the classifier.",random_signed:"Cooperative and competitive degrees match the structured model, but their locations are degree-preserving rewires.",structured_signed:"Cooperation is restricted within four predefined channel groups; competition connects channels across groups."};
const canvas=document.querySelector("#network"),ctx=canvas.getContext("2d");
function fmt(value,digits=3){return Number(value).toFixed(digits)}
function resize(){const box=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=box.width*dpr;canvas.height=box.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);drawNetwork()}
function setupModes(){const picker=document.querySelector("#mode-picker");Object.keys(labels).forEach(mode=>{const button=document.createElement("button");button.textContent=labels[mode];button.dataset.mode=mode;button.onclick=()=>{state.mode=mode;updateArchitecture()};picker.append(button)});updateArchitecture()}
function updateArchitecture(){document.querySelectorAll("#mode-picker button").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.mode));document.querySelector("#architecture-copy").textContent=descriptions[state.mode];document.querySelector("#coop-degree").textContent=state.mode==="standard"?"0":"4 / channel";document.querySelector("#comp-degree").textContent=state.mode==="standard"?"0":"4 / channel";document.querySelector("#network-label").textContent=labels[state.mode];drawNetwork()}
function drawNetwork(){if(!state.data)return;const graph=state.data.graphs[state.mode],w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const nodes=graph.nodes.map(n=>({...n,px:n.x*w,py:n.y*h})),byId=Object.fromEntries(nodes.map(n=>[n.id,n]));[0,1,2,3].forEach(group=>{const members=nodes.filter(n=>n.group===group),cx=members.reduce((a,n)=>a+n.px,0)/members.length,cy=members.reduce((a,n)=>a+n.py,0)/members.length;ctx.beginPath();ctx.arc(cx,cy,Math.min(w,h)*.16,0,Math.PI*2);ctx.fillStyle=`rgba(${group===0?"81,221,178":group===1?"114,167,255":group===2?"200,140,255":"255,155,114"},.045)`;ctx.fill();ctx.strokeStyle="#293243";ctx.stroke();ctx.fillStyle="#687386";ctx.font="10px system-ui";ctx.fillText(`GROUP ${group+1}`,cx-23,cy)});graph.edges.forEach(edge=>{const a=byId[edge.source],b=byId[edge.target];ctx.globalAlpha=edge.sign==="cooperative"?.16:.12;ctx.strokeStyle=edge.sign==="cooperative"?"#51ddb2":"#ff6f91";ctx.lineWidth=.55;ctx.beginPath();ctx.moveTo(a.px,a.py);ctx.lineTo(b.px,b.py);ctx.stroke()});ctx.globalAlpha=1;const colors=["#71d7b4","#7eb0ff","#c88cff","#ff9b72"];nodes.forEach(n=>{ctx.beginPath();ctx.arc(n.px,n.py,3.2,0,Math.PI*2);ctx.fillStyle=colors[n.group];ctx.fill()})}
function setupLearning(){const seed=document.querySelector("#seed"),mode=document.querySelector("#learning-mode");state.data.confirmation.seeds.forEach(value=>seed.add(new Option(`Seed ${value}`,value)));Object.keys(labels).forEach(value=>mode.add(new Option(labels[value],value)));seed.value=state.seed;mode.value=state.mode;seed.onchange=()=>{state.seed=Number(seed.value);updateLearning()};mode.onchange=()=>{state.mode=mode.value;updateLearning();updateArchitecture()};document.querySelector("#experience").oninput=event=>{state.experience=Number(event.target.value);updateLearning()};updateLearning();const contrast=state.data.confirmation.primary_contrast;document.querySelector("#primary-difference").textContent=`${contrast.mean_difference>=0?"+":""}${fmt(contrast.mean_difference,5)}`;document.querySelector("#primary-ci").textContent=`[${fmt(contrast.bootstrap_95_ci[0],5)}, ${fmt(contrast.bootstrap_95_ci[1],5)}]`;document.querySelector("#primary-p").textContent=fmt(contrast.two_sided_exact_sign_flip_p,3)}
function selectedRun(){return state.data.confirmation.runs.find(run=>run.seed===state.seed&&run.mode===state.mode)}
function updateLearning(){if(!state.data)return;document.querySelector("#experience-value").value=state.experience;const run=selectedRun();if(!run)return;document.querySelector("#class-order").textContent=`order · ${run.class_order.join(" → ")}`;const board=document.querySelector("#experience-board");board.replaceChildren();run.experiences.forEach((classes,index)=>{const seen=index<state.experience,accuracy=seen?run.accuracy_matrix[state.experience-1][index]:null,card=document.createElement("article");card.className=`experience-card ${seen?"seen":""} ${index===state.experience-1?"current":""}`;card.innerHTML=`<header><small>Experience ${index+1}</small><div class="class-pair">${classes.map(c=>`<span class="class-chip">class ${c}</span>`).join("")}</div></header><div class="retention"><i style="height:${accuracy===null?0:accuracy*100}%"></i></div><div class="retention-label"><span>${seen?"retained accuracy":"unseen"}</span><strong>${accuracy===null?"—":fmt(accuracy*100,1)+"%"}</strong></div>`;board.append(card)});const metrics=[["Incremental accuracy",run.average_incremental_accuracy],["Final accuracy",run.final_average_accuracy],["Average forgetting",run.average_forgetting],["New-class acquisition",run.mean_new_experience_accuracy]];document.querySelector("#run-metrics").innerHTML=metrics.map(([k,v])=>`<div><dt>${k}</dt><dd>${fmt(v*100,1)}%</dd></div>`).join("");document.querySelector("#run-verdict").textContent=state.mode==="structured_signed"?"This run shows what the structured model did, not whether structure helped. The claim comes only from its paired contrast across all ten seeds.":state.mode==="random_signed"?"This is the degree- and capacity-matched topology control used in the primary comparison.":"The standard CNN is a reference condition; the frozen primary contrast is structured versus random signed."}
function bar(label,value,max,structured=false,suffix=""){return `<div class="bar-row ${structured?"structured":""}"><span>${label}</span><div class="bar-track"><i style="width:${Math.min(100,Math.abs(value)/max*100)}%"></i></div><strong>${fmt(value,3)}${suffix}</strong></div>`}
function setupMechanism(){const runs=state.data.bottleneck.runs,mean=(mode,key)=>runs.filter(r=>r.mode===mode).reduce((s,r)=>s+r[key],0)/5;document.querySelector("#engagement-comparison").innerHTML=bar("Random gap",mean("random_signed","post_signed_edge_tuning_gap"),.7)+bar("Structured gap",mean("structured_signed","post_signed_edge_tuning_gap"),.7,true)+bar("Bypass effect",mean("structured_signed","pathway_accuracy_effect"),.4,true);const random=state.data.drift.transition_curves.random_signed,structured=state.data.drift.transition_curves.structured_signed;document.querySelector("#drift-grid").innerHTML=structured.map((row,i)=>`<div class="transition-cell"><span>after exp ${row.after_experience}</span><strong>+${fmt(row.old_group_profile_cosine_drift-random[i].old_group_profile_cosine_drift,3)}</strong><span>excess group drift</span></div>`).join("");const summary=state.data.interventions.structured_signed;document.querySelector("#intervention-comparison").innerHTML=bar("Control drift",summary.control.mean_group_drift,.015)+bar("Selective drift",summary.selective.mean_group_drift,.015,true)+bar("Control final",summary.control.final_average_accuracy,.5)+bar("Selective final",summary.selective.final_average_accuracy,.5,true)}
document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(el=>el.classList.remove("active"));tab.classList.add("active");document.querySelector(`#${tab.dataset.view}`).classList.add("active");if(tab.dataset.view==="architecture")requestAnimationFrame(resize)});addEventListener("resize",resize);
fetch("data/neuroai-atlas.json").then(r=>r.json()).then(data=>{state.data=data;setupModes();setupLearning();setupMechanism();resize()}).catch(error=>{document.querySelector(".status span").textContent=`Could not load data: ${error.message}`});
